language: node_js
node_js:
  - '8'
before_deploy:
  - yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAGES_TOKEN
    local_dir: ./release
    email: 'embbnux@embbnux.com'
    name: 'Embbnux Ji'
